# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaMQTT' 
  pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'
end
